name: API Automation Tests

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:6
        ports:
          - 27017:27017

    env:
      MONGO_URI: mongodb://localhost:27017/testdb
      BASE_URL: http://localhost:8001
      ADMIN_EMAIL: john@example.com
      ADMIN_PASSWORD: Admin@123

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Start backend
        run: |
          nohup npm run dev &
          sleep 15

      - name: Ensure Admin Exists
        run: node scripts/ensureAdmin.js

      - name: Login Admin + Update Env
        run: node scripts/loginAdmin.js

      - name: Register Worker User
        run: node scripts/registerWorker.js

      - name: Run API Tests
        run: npm run test:api